### ISSUE TITLE
Kit protected components? Conditionals?

### ISSUE THREAD

**Issue by rchrdnsh** [supabase-community/auth-helpers#192]
kit protected components? Conditionals?

I notice there is a protected routes helper, but could that work with protected components and/or {#if} blocks?

For example, I would want both guests and members to be able to visit the same route, but only the members who are logged in to see certain content at that route in the form of components and/or if {#if} blocks meet that condition.

could these helpers help with that? Would there be another way to go about it?

**Comment by david-plugge** [comment]
Im not sure if im missing something, but i guess you can just check if there is a user in $session.user

**Comment by rchrdnsh** [comment]
hmmmm...so do we need a protected route helper? Is that more challenging? I don't really understand the helpers yet, so bear with me on this, just trying to understand it all better :-)

**Comment by philip-weber** [comment]
I guess what david-plugge said would help you. After the users logged in their `user` is stored in the `session` store. You can access this with `$session.user`.

One way could be to check in your route if the user is logged in by checking `$session.user` and then conditionally render different components.

I have modified the [Basic Setup example](https://github.com/supabase-community/auth-helpers/tree/main/packages/sveltekit#basic-setup) from the docs, to render different components instead of different `h1` tags:
```js
// src/routes/index.svelte
<script>
import { session } from '$app/stores';
import GuestComponent from '$lib/components/guest/GuestComponent.svelte';
import MemberComponent from '$lib/components/member/MemberComponent.svelte';
</script>

{#if !$session.user}
  <GuestComponent />
{:else}
  <MemberComponent />
{/if}
```

You can also find a more elaborate version in the docs if you are fine with client-side fetching. [Client-side data fetching with RLS](https://github.com/supabase-community/auth-helpers/tree/main/packages/sveltekit#client-side-data-fetching-with-rls)

Hope this helps a bit

**Comment by silentworks** [comment]
This has been answered.
