### ISSUE TITLE
SvelteKit - Possibility to extend user in hooks.js with a profile

### ISSUE THREAD

**Issue by kvetoslavnovak** [supabase-community/auth-helpers#202]
I am trying extend the user returned in hooks.js also with his/her associated data from Supabase profile table. 
Unfortunately it seems not too obvious how to do this at this moment.  SvelteKit documentation expects us to do such things in handle function but handleAuth in handle function provides some kind of abstraction which I do not want to touch,maybe to extend the event.locals.user in getSession is a better way ?

This is my working solution. But I am not sure if it is not rather a hack.

```js
import { handleAuth } from '@supabase/auth-helpers-sveltekit';
import { sequence } from '@sveltejs/kit/hooks';
import { supabaseServerClient } from '@supabase/auth-helpers-sveltekit';

export const handle = sequence( 
	...handleAuth({
		cookieOptions: { lifetime: 1 * 365 * 24 * 60 * 60 }
	})
);

export const getSession = async (event) => {
	const { user, accessToken } = event.locals;
	
	if (user) {
		const { data } = await supabaseServerClient()
		.from('customer_profiles')
		.select('*')
		.eq('id', user.id)
		.single();
		user.profile = data;
	}

	return {
		user,
		accessToken
	};
};

```

And this is my way if there is Supabase  RLS enabled based on user id. 

```js
import { handleAuth } from '@supabase/auth-helpers-sveltekit';
import { sequence } from '@sveltejs/kit/hooks';
import { supabaseServerClient } from '@supabase/auth-helpers-sveltekit';

export const handle = sequence( 
	...handleAuth({
		cookieOptions: { lifetime: 1 * 365 * 24 * 60 * 60 }
	})
);

export const getSession = async (event) => {
	const { user, accessToken } = event.locals;
	
	if (user) {
		const { data } = await supabaseServerClient(accessToken)
		.from('customer_profiles')
		.select('*')
		.eq('id', user.id)
		.single();
		user.customer_profile = data;
	}

	return {
		user,
		accessToken
	};
};
```

Is there any recommended practice how to do this? 
Or if this is really a right way to do it I may add this information to a documentation. 
Thank you very much

**Comment by silentworks** [comment]
Since you can chain multiple hook functions with the `sequence` helper just create another hook and do what you need there. You can see an example in my waiting-list project.

handleProfile file → https://github.com/silentworks/waiting-list/blob/main/src/lib/handleProfile.js
hooks file → https://github.com/silentworks/waiting-list/blob/main/src/hooks.js#L5

**Comment by dragonsnapx** [comment]
I was trying to figure this out too, only question is that `handle()` runs every time the user submits a request - which means it'll query the database every time the user navigates. Would it be better to store it in a session and only refresh it when the user logs in or logs out?

**Comment by kvetoslavnovak** [comment]
Exactly. As getSession stores it automatically you can access the user on the front end using  

```svelte
//__layout.svelte
<script>
	import { session } from '$app/stores';
</script>
{$session?.user}
```

```js
// endpoint.js
export const GET = async ({ locals }) => {
	return {
		locals.user
	};
};
```

**Comment by kvetoslavnovak** [comment]
Just in case if someone wants to enrich your user in the load function you can do it like this:

```js
import { handleAuth } from '@supabase/auth-helpers-sveltekit';
import { sequence } from '@sveltejs/kit/hooks';
import { supabaseServerClient } from '@supabase/auth-helpers-sveltekit';

async function addCustomer({ event, resolve }) {
	if (event.locals.user) {
	const { data } = await supabaseServerClient(event.locals.accessToken)
		.from('customer_profiles')
		.select('*')
		.eq('id', event.locals.user.id)
		.single();
		event.locals.user.customer_profile = data;
	}
	const result = await resolve(event);
	return result;
  }

export const handle = sequence( 
	...handleAuth({
		cookieOptions: { lifetime: 1 * 365 * 24 * 60 * 60 }
	}), 
	addCustomer
);

export const getSession = async (event) => {
	const { user, accessToken } = event.locals;
	return {
		user,
		accessToken
	};
};
```

**Comment by Everduin94** [comment]
Sorry for commenting on a closed issue and I may just be missing something.

Doesn't making this call in your hook.server.ts prolong the time to render the corresponding +layout.svelte/+page.svelte? 

i.e. if the call to `customer_profiles` takes 200ms it will add 200ms to your initial load.

I have some properties like `theme` that I'd like to be available on initial load during SSR (so the theme doesn't flash from default to the user's theme). Since it seems like auth.user cannot be extended, is the above solution the only way to achieve this?

i.e. If these properties could be made available on event.locals.user then the second call wouldn't have to be made, but I'm assuming this is not possible?
